import type { Metadata } from "next";

import "./globals.css";
import AppProvider from "./providers/AppProvider";
import AppHeader from "./layouts/AppHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppProvider>
        <body>
          <AppHeader />
          <div className="flex min-h-screen flex-col items-center justify-between py-6 px-4 md:px-16 bg-[#EDDCF5]">
            {children}
          </div>
        </body>
      </AppProvider>
    </html>
  );
};
