import type { Metadata } from "next";

import "./globals.css";
import AppProvider from "./providers/AppProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppProvider>
        <body className="flex min-h-screen flex-col items-center justify-between py-6 md:py-12 px-6 md:px-12">{children}</body>
      </AppProvider>
    </html>
  );
};
